package:
  name: 'tofu'
  # version: {{ environ['VERSION'] }}
  version: {{ '1.7.0' }}

source:
  git_url: https://github.com/ToFuProject/tofu.git
  # git_rev: {{ environ['REV'] }}
  git_rev: {{ '1.7.0' }}

#build:
  #script_env:
    #- PKG_REAL
    #- TRAVIS_BRANCH

requirements:

  # build: necessary for build.sh
  # here same as run, as we are using cython
  build:
    - python
    - setuptools >=40.8.0
    - setuptools_scm
    - numpy
    - Cython >=0.26
    - pytest
    # - pygments


  # for running the library
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - contourpy
    - Cython >=0.26
    # - pygments
    - requests
    - svg.path
    - Polygon3
    - bsplines2d >=0.0.6
    - pytest
    # - scikit-sparse   # not available on Windows
    # - scikit-umfpack  # not available on Windows

test:
  requires:
    - pytest
  imports:
    - tofu

about:
  home: https://github.com/ToFuProject/tofu
  license: MIT
  license_file: LICENSE.txt
  summary: Tomography for Fusion

# conda build -c tofuproject conda_recipe/
