name: Complete testing matrix

on:
  push:
    branches: [ devel, master ]
  pull_request:
    branches: [ devel, master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.8']  #, '3.7', '3.8,' '3.9']
        os: [ubuntu-latest]  # , macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
         pip install --upgrade pip
         pip install flake8 pytest coverage wheel
         pip install -r requirements.txt
    - name: install tofu
      run: |
        pip install -e ".[dev]" --no-build-isolation
    - name: Test with pytest and coverage
      run: |
              pytest tofu/tests/tests01_geom/test_01_GG.py::test12_Ves_Smesh_Lin -s
