name: Complete testing matrix

on:
  push:
    branches: [ devel, master ]
  pull_request:
    branches: [ devel, master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
         $CONDA/bin/conda config --append channels conda-forge
         $CONDA/bin/conda install flake8, pytest, coverage 
         $CONDA/bin/conda env update --file requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: install tofu
      run: |
        pip install -e ".[dev]" --no-build-isolation
    - name: Test with pytest and coverage
      run: |
              coverage run --source=tofu/ -m pytest tofu/tests -v -x --durations=10
